DEVICE: "cuda"
MODEL: "Unet"
LOSS: "BCEL"
OPTIMIZER:
  NAME: "ADAM"
  LR: 0.05
SCHEDULER:
  NAME: "EXPONENTIAL"
  GAMMA: 0.95
DATA:
  root: "data/database_expanded"
  device: "cuda"
  type: "N 4CH"
TRANSFORM: "default"
TRAIN:
  TRAIN: 0.9
  TEST: 0
  VAL: 0.1
  BATCH_SIZE: 8
  EPOCHS: 5
  KFOLD: 10